@baseUrl = http://localhost:3333

### Create account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "123456"
}

### Sign in
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "pedro.viniciuscarvalho1@gmail.com",
  "password": "123456"
}